name: al_quran
description:

version: 2.5.6+11

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # utils
  #share: ^2.0.4
  recase: ^4.0.0
  shimmer: ^3.0.0
  url_strategy: ^0.3.0
  cupertino_icons: ^1.0.3

  # network
  dio: ^5.3.2
  url_launcher: ^6.0.12
  
  # state management
  provider: ^6.1.2
  equatable: ^2.0.3
  flutter_bloc: ^8.1.3

  # icon pack
  iconsax: ^0.0.8

  # cache
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.8

  # app info
  package_info_plus: ^8.0.3
  collection: ^1.17.1

  qibla_direction: ^1.0.1
  geolocator: ^13.0.2
  sensors_plus: ^6.1.1
  flutter_local_notifications: ^18.0.1
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  flutter_timezone: ^4.0.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

    # flutter code
  flutter_lints: ^5.0.0
  # cache local storage
  build_runner: ^2.1.5
  hive_generator: ^2.0.0
  # launcher icons
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo6.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/intro/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 600
        - asset: fonts/Poppins-Light.ttf
          weight: 200
        - asset: fonts/Poppins-Bold.ttf
          weight: 900
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-SemiBold.ttf
    - family: ShareIcon
      fonts:
        - asset: fonts/ShareIcon.ttf
    - family: Noor
      fonts:
        - asset: fonts/noor-regular.ttf
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
    - family: AmiriQuran
      fonts:
        - asset: fonts/AmiriQuran-Regular.ttf
